
@startuml
title Career Consultant Runs Career Counselling Session
participant ":CareerConsultant" as career
participant ":UnregisteredUser" as unregistered
' participant ":CounsellingTimetable" as timetable
participant ":CounsellingBooking" as counsellingBooking
participant ":CounsellingSession" as counsellingSession
participant ":CounsellingTimetable" as timetable

' career consultant creates counselling timetable
career -> timetable : createCounsellingTimetable()
activate career
activate timetable
timetable --> career : Timetable

' user views and books counselling timetable
unregistered -> timetable : viewCounsellingTimetable()
activate unregistered
timetable --> unregistered : Timetable

unregistered -> counsellingBooking : bookCounsellingSession()
activate counsellingBooking
counsellingBooking --> unregistered : Session Details
deactivate counsellingBooking

' cancel session before session starts
alt Career Consultant Cancels Session Before It Starts
    career -> timetable : cancelSession()
    ' timetable --> career : Message: Session Cancelled
end
alt Unregistered User Cancels Session Before It Starts
    unregistered -> timetable : cancelSession()
    ' timetable -> career : Message: Session Cancelled
end

' if counselling session not cancelled before session
alt Counselling Sesson Not Cancelled
    unregistered -> counsellingSession : joinCounsellingSession()
    activate counsellingSession
    career -> counsellingSession : joinCounsellingSession()
    ' career -> counsellingSession : Run Counselling Session

    loop Session Active
        unregistered -> counsellingSession : sendVideo()
        counsellingSession --> unregistered : receiveVideo()
        unregistered -> counsellingSession : sendAudio()
        counsellingSession --> unregistered : receiveAudio()
        unregistered -> counsellingSession : postChatMessage()
        counsellingSession --> unregistered : receiveChatMessage()

        career -> counsellingSession : sendAudio()
        counsellingSession --> career : receiveAudio()
        career -> counsellingSession : sendVideo()
        counsellingSession --> career : receiveVideo()
        career -> counsellingSession : postChatMessage()
        counsellingSession --> career : receiveChatMessage()

        alt End Counselling Session
            career -> counsellingSession : endSession()
        end
        
        deactivate counsellingSession
    end

' counselling session cancelled before session
else Counselling Sesson Cancelled
    timetable --> unregistered : Message: Session Cancelled
    deactivate unregistered
    timetable --> career : Message: Session Cancelled
    deactivate timetable
    deactivate career

end

@enduml