
@startuml
' title Finance Manager Refunds Course Registration Fee
title "Trainee Lodges A Registration Fee Refund Request\nWhich Is Addressed By The Finance Manager"
participant ":Trainee" as trainee
participant ":FinanceManager" as finance
participant ":System" as system
participant "paymentMethod:Trainee" as paymentMethod

alt Trainee Is Registered
    trainee -> finance : cancelTraining()
    activate trainee
    activate finance
    
    alt More Than 24 Hours\nBefore First Session
        finance -> system : approveRefund()
        activate system

        alt Original Payment\nMethod Is Active
            system -> paymentMethod : depositAmount()
            activate paymentMethod
        else Original Payment\nMethod Not Active
            system --> finance : Refund Failed
            finance --> trainee : Refund Denied
            deactivate finance
        end
    end

    alt Training Course\nHas Not Started
        system -> system : makePositionAvailable()
    end

    system -> trainee : changeStatusToUnregistered()
    deactivate system
    paymentMethod --> trainee : Receive Refund
    deactivate paymentMethod
    deactivate trainee
end

@enduml