@startuml
title "IT Administrator Records Face To Face Training Then Uploads Recording"
participant ":ITadministrator" as itAdmin
participant ":TrainingSession" as trainingSession
participant ":System" as system

activate system

loop Face To Face Training Sessions Scheduled
    alt Face To Face Training Session Starting Now
    itAdmin -> trainingSession : startRecording()
    activate trainingSession
    activate itAdmin
    itAdmin -> system : setRecordingAutomaticStopTime()
    
        loop Face To Face Training Session In Progress
            alt Training Session Finished
                system -> trainingSession : stopRecording()
                deactivate trainingSession
            end
        end
        
    system --> itAdmin : Recording Finished

    loop Recording Uploaded Successfully
        itAdmin -> system : uploadRecording()
        note right: The IT Administrator should confirm that\nrecording uploaded successfully
        system --> itAdmin : uploadSuccess()
        deactivate itAdmin
    end
    end
    

end
@enduml