@startuml
' title "Manager Collects Trainee Feedback Poll"
title Manager Creates A Poll That Is Responded To By A Trainee
participant ":Manager" as manager
participant ":FeedbackPoll" as feedback
participant ":System" as system
participant ":Trainee" as trainee

manager -> feedback : createPoll()
activate manager
activate feedback
feedback -> system : Notification: Poll Ready
activate system

alt Training Course Has Finished AND Was Completed By At Least One Trainee
    system -> trainee : releasePoll()  
    activate trainee
    note right: If training course has finished\nand was completed by at least\none Trainee, the system releases\nthe poll
    trainee --> feedback : completePoll()
    deactivate trainee
    feedback -> system : storePoll()            
    note right: The system stores the feedback poll

    alt At Least One Trainee Completed Feedback Poll
        system -> manager : Notification: Poll Results Ready
        deactivate system
        manager --> feedback : viewPollResults()
        deactivate feedback
        deactivate manager
    end
end

@enduml