@startuml
title "Trainer And Trainee Attend Training Session"

participant ":Trainer" as trainer
participant "trainer:TrainingResources" as trainerResources
participant ":TrainingSession" as trainingSession
participant "trainee:TrainingResources" as traineeResources
participant ":Trainee" as trainee
participant ":System" as system

loop Training Session Scheduled
    alt Training Session Starting Now
        ' open room
        system -> trainingSession : openTrainingSessio()
        activate system
        activate trainingSession
        system -> trainingSession : recordTrainingSession()
        note left: The system automatically opens the\nonline training room when a session\nstarts and records the session
        ' access resources
        trainer -> trainerResources : accessTrainingResources()
        activate trainer
        activate trainerResources
        ' join session
        trainerResources -> trainingSession : joinTrainingSession()
        note right: A training session must be accessed\nthrough the user training resources
        trainee -> traineeResources : accessTrainingResources()
        activate trainee
        activate traineeResources
        traineeResources -> trainingSession : joinTrainingSession()
        
        ' trainer session
        loop Training Session Active
            trainer -> trainingSession : sendChatMessage()
            trainingSession --> trainer : receiveChatMessage()
            trainer -> trainingSession : sendAudio()
            trainingSession --> trainer : receiveAudio()
            trainer -> trainingSession : sendVideo()
            trainingSession --> trainer : receiveVideo()
        ' end
                
        ' trainee session
        ' loop Training Session Active
            trainee -> trainingSession : sendChatMessage()
            trainingSession --> trainee : receiveChatMessage()
            trainee -> trainingSession : sendAudio()
            trainingSession --> trainee : receiveAudio()
            trainee -> trainingSession : sendVideo()
            trainingSession --> trainee : receiveVideo()

            ' end training session
            alt End Training Session
                trainer -> trainingSession : closeTrainingSession()
                note right: The Trainer can end the training session at any time

                ' upload recording
                system -> trainingSession : uploadSessionRecording()
                note left: The system automatically uploads the session recording
                deactivate trainingSession
            end
        end
        
        

    end
end

@enduml