@startuml
title "Unregistered User Registers For Training Course"

participant ":UnregisteredUser" as unregistered
participant ":TrainingCourses" as training
participant ":Trainer" as trainer
participant ":System" as system
participant ":Trainee" as trainee
participant ":TrainingResources" as trainingResources

' activate system

' view courses
unregistered -> training : ViewAllCourseOptions()
activate unregistered
activate training
training --> unregistered : All Course Options

alt
    unregistered -> training : ViewOnlineCourseOptions()
    training --> unregistered : Online Course Options
else
    unregistered -> training : ViewFaceToFaceCourseOptions()
    training --> unregistered : Face To Face Course Options
end

' Enquiry
unregistered -> trainer : submitEnquiry()
activate trainer
trainer --> unregistered : respondToEnquiry()
deactivate trainer

' select training course
loop Course Selection Fail
    unregistered -> training : selectTrainingCourse()
    alt Position Available In Selected Course
        training --> unregistered : Selected Course
        deactivate training
    end
end

' register for training
unregistered -> system : registerForTrainingCourse()
activate system
loop Personal Information Fail
    unregistered -> system : enterPersonalInformation(name, DOB, address, contactNumber,\n                                                      emergencyContactNumber, email)

    alt Personal Information Valid
        system --> unregistered : Personal Information
    else Personal Information Invalid
        system --> unregistered : Error Message
    end 
end

loop Username, Registration ID, Password Fail
    unregistered -> system : enterRegistrationInformation(username, registrationID, password)

    alt Registration Information Valid
        system --> unregistered : Registration Information
    else Registration Information Invalid
        system --> unregistered : Error Message
    end 
end

' Dispaly fee and payment options
system -> unregistered : displayFinalFee(amount)
system -> unregistered : displayPaymentOptions(payPal, creditCard, bankTransfer)

' select payment method
loop Payment Fail
    unregistered -> system : selectPaymentMethod(paymendMethod)
    system --> unregistered : displayPaymentMethod()
    unregistered -> system : makePayment()

    alt Payment Valid
        system --> unregistered : Payment Confirmation
    else Payment Invalid
        system --> unregistered : Error Message
    end 
end

alt Payment Success
    system -> unregistered : sendRegistrationInformation(username, registrationID, password)
    system -> unregistered : setUserStatus(Trainee)
    deactivate unregistered
end
note right: After registration, the system changes the\n status from Unregistered User to Trainee

' access training resources
system -> trainee : newTrainee(unregisteredUser)
deactivate system
deactivate unregistered
activate trainee
trainee -> trainingResources : accessCourseResources(username, password)
activate trainingResources
trainingResources --> trainee : Course Resources

@enduml