@startuml
' title "Manager Collects Trainee Feedback Poll"
title Manager Creates A Poll That Is Responded To By A Trainee
participant ":Manager" as manager
participant ":FeedbackPoll" as feedback
participant ":System" as system
participant ":Trainee" as trainee
participant ":TrainingCourse" as trainingCourse

manager -> trainingCourse : selectTrainingCourse()
activate manager
activate trainingCourse
trainingCourse --> manager : Training Course ID
deactivate trainingCourse
manager -> feedback : createPoll()
activate feedback
feedback --> manager : Feedback Poll
deactivate feedback
manager -> system : releasePoll()
' feedback -> system : Notification: Poll Ready
activate system

alt Training Course Has Finished AND Was Completed By At Least One Trainee
    system -> trainee : releasePoll()  
    activate trainee
    note right: If training course has finished\nand was completed by at least\none Trainee, the system releases\nthe poll
    trainee -> system : completePoll()
    deactivate trainee
    system -> system : storePoll()            
    note right: The system stores the feedback poll

    alt At Least One Trainee Completed Feedback Poll\nAnd Poll Submission Due Date Has Passed
        system -> manager : Notification: Poll Results Ready
        manager -> system : viewPollResults()
        system --> manager : Poll Results
        deactivate system
        deactivate feedback
        deactivate manager
    end
end

@enduml